### ISSUE TITLE
 ReferenceError: elementsMatch is not defined

### ISSUE THREAD

**Issue by aduyng** [bruderstein/unexpected-react-shallow#9]
Hello, 

I have used this package in my testing setup using webpack, babel, and mocha. Webpack and babel will transform my source and test files into bundle.js then mocha will run on this file. For some reasons, I encountered the following error every time I run mocha. 

```
  1) components/base-widgets/button should render correctly with DEFAULT random parameters:
     ReferenceError: elementsMatch is not defined
      at oathbreaker (webpack:///./~/unexpected/lib/oathbreaker.js:47:1)
      at Function.withError (webpack:///./~/unexpected/lib/createWrappedExpectProto.js:36:1)
      at Function.<anonymous> (webpack:///./~/unexpected-react-shallow/src/lib/assertions.js:17:1)
      at executeExpect (webpack:///./~/unexpected/lib/Unexpected.js:1056:1)
      at webpack:///./~/unexpected/lib/Unexpected.js:1020:1
      at Function.callInNestedContext (webpack:///./~/unexpected/lib/createWrappedExpectProto.js:60:1)
      at wrappedExpect (webpack:///./~/unexpected/lib/Unexpected.js:1019:1)
      at Function.<anonymous> (webpack:///./~/unexpected-react-shallow/src/lib/assertions.js:52:1)
      at executeExpect (webpack:///./~/unexpected/lib/Unexpected.js:1056:1)
      at Unexpected.expect (webpack:///./~/unexpected/lib/Unexpected.js:1061:1)
      at Context.<anonymous> (webpack:///./~/chai/index.js:23:9)
      ....
```

Here is an example of the component under test: 

``` javascript
import React, { Component } from 'react';
import classNames from 'classnames';

import './styles/button';

export default class Button extends Component {

    static propTypes = {
        id: React.PropTypes.string,
        onClick: React.PropTypes.func,
        className: React.PropTypes.string,
        disabled: React.PropTypes.bool,
        children: React.PropTypes.oneOfType([React.PropTypes.string, React.PropTypes.arrayOf(React.PropTypes.element)])
    };

    onClick(e, props) {
        if (this.props.onClick) {
            this.props.onClick(e, props);
        }
    }

    render() {
        const className = classNames('dxp-button', this.props.className);
        return (
            <button id={this.props.id} className={className} onClick={(e) => this.onClick(e, this.props)} disabled={this.props.disabled}>
                {this.props.children}
            </button>);
    }
}
```

And here is the test code: 

``` javascript
import {expect} from 'chai';
import React from 'react';
import Button from 'components/base-widgets/button';
import TestUtils from 'react-addons-test-utils';
import Chance from 'chance';
import unexpected from 'unexpected';
import unexpectedReactShallow from 'unexpected-react-shallow';

const expectDOM = unexpected.clone()
    .installPlugin(unexpectedReactShallow);
const chance = new Chance();

describe('components/base-widgets/button', function () {
    it('should render correctly with DEFAULT random parameters', function () {
        const props = {
            className: chance.word(),
            id: chance.guid(),
            disabled: chance.bool()
        };
        const children = ['Button Name'];
        const shallowRenderer = TestUtils.createRenderer();
        shallowRenderer.render(React.createElement(Button, props, children));
        expectDOM(shallowRenderer, 'to have rendered', (
            <button id={props.id} className={`dxp-button ${props.className}`} disabled={props.disabled}>{'Button Name'}</button>
        ));
    });
});
```

Here are packages I used: 

```
"react-addons-test-utils": "^0.14.0",
"unexpected": "^10.0.1",
"unexpected-react-shallow": "^0.6.1",
"react": "^0.14.0",
```

Do you know why it is happening?

**Comment by bruderstein** [comment]
Would it be possible to share your webpack config, or at least enough of it to try to replicate it? I don't use webpack, so I don't know how to configure it properly.

Thank!

**Comment by aduyng** [comment]
Here is my webpack config

``` javascript
var path = require('path');
var webpack = require('webpack');

module.exports = {
    devtool: 'inline-source-map',
    target: 'node',
    entry: [
        './test/index'
    ],
    output: {
        path: path.join(__dirname, 'tmp'),
        filename: 'js/bundle.js',
        publicPath: '/'
    },
    resolve: {
        extensions: ['', '.js', '.scss', '.less'],
        alias: {
            styles: path.join(__dirname, 'app/common/styles'),
            actions: path.join(__dirname, 'app/common/actions'),
            components: path.join(__dirname, 'app/common/components'),
            reducers: path.join(__dirname, 'app/common/reducers'),
            selectors: path.join(__dirname, 'app/common/selectors'),
            services: path.join(__dirname, 'app/services'),
            utils: path.join(__dirname, 'app/common/utils'),
            features: path.join(__dirname, 'app/features'),
            images: path.join(__dirname, 'public/images')
        }
    },
    module: {
        loaders: [
            {
                test: /\.jsx?$/,
                loader: 'babel',
                query: {
                    compact: false
                },
                exclude: /node_modules/,
                include: [path.join(__dirname, 'app'), path.join(__dirname, 'test')]
            },
            {
                test: /\.(scss|less|json)$/,
                loader: 'null'
            }
        ]
    }
};
```

And here is my gulp tasks:

``` javascript
import testWebpackConfig from './webpack-test.config';

gulp.task('webpack:test', function (callback) {
    let config = Object.create(testWebpackConfig);
    return webpack(config, function (err, stats) {
        if (err) {
            throw new gutil.PluginError('test:unit', err);
        }
        gutil.log('test:unit', stats.toString({
            colors: true
        }));
        callback();
    });
});
gulp.task('test', function (callback) {
    runSequence('webpack:test', 'mocha', callback);
});
```

Thanks.

**Comment by bruderstein** [comment]
Ok, I've built a repo with this all in (minus gulp, but that shouldn't be important), and it works - the test passes. 

Can you try deleting your node_modules/unexpected-react-shallow, and rerunning the `npm install`. What's odd is, is that line 17 of `assertions.js` is actually `assertElementsMatch`, which changed in a recent update - I wonder if you just have a buggy install?

If that doesn't change anything, I'll commit and push this repo, then you can take a look and see if you can replicate it.

What is very cool though, is that I've been able to replicate issue #4 with this setup, so thank you for sharing all the files!

**Comment by bruderstein** [comment]
Pushed the repo here - let me know if you can repo it with that: https://github.com/bruderstein/shallow-issue-9

**Comment by bruderstein** [comment]
I'm going to close this as until we can get a repro going, it's going to be very hard to fix. Also no feedback for a while. Feel free to re-open if you have new information.
